apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: linkding-backup-creds-infisical
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-d-s7-g

        envSlug: "prod" # "dev", "staging", "prod"
        secretsPath: "/garage/linkding"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-secrets-operator

  managedKubeSecretReferences:
    - secretName: linkding-backup-creds
      secretNamespace: linkding
      creationPolicy: Owner
