# Install prometheus operator crds
crds:
  enabled: true

prometheus:
  prometheusSpec:
    remoteWriteDashboards: false
    serverSideApply: true
    retention: 1d
    retentionSize: 40Gi # Reasonable 80%-85% of pvc max

    # Prometheus Persistence
    storageSpec:
      volumeClaimTemplate:
        spec:
          # storageClassName: ""
          resources:
            requests:
              storage: 50Gi
    resources:
      requests:
        memory: 2Gi
        cpu: 200m
      limits:
        memory: 4Gi
        cpu: 2

  # affinity:
  #   nodeAffinity:
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #       - weight: 100
  #         preference:
  #           matchExpressions:
  #             - key: kubernetes.io/hostname
  #               operator: In
  #               values:
  #                 - worker

grafana:
  enabled: true
  # Grafana secret
  admin:
    existingSecret: "grafana-secret"
    userKey: admin-user
    passwordKey: admin-password

  # Grafana persistence
  persistence:
    enabled: true
    type: sts
    # storageClassName: ""
    accessModes:
      - ReadWriteOnce
    size: 20Gi

  ingress:
    enabled: false

  # affinity:
  #   nodeAffinity:
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #       - weight: 100
  #         preference:
  #           matchExpressions:
  #             - key: kubernetes.io/hostname
  #               operator: In
  #               values:
  #                 - worker

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          # storageClassName: ""
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

    # affinity:
    #   nodeAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - weight: 100
    #         preference:
    #           matchExpressions:
    #             - key: kubernetes.io/hostname
    #               operator: In
    #               values:
    #                 - worker

prometheusOperator:
  admissionWebhooks:
    patch:
      enabled: true
  tls:
    enabled: false
