apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/secrets.yaml
  - resources/db.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/ingress.yaml
