apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: linkding-env-vars-infisical
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-d-s7-g

        envSlug: "prod" # "dev", "staging", "prod"
        secretsPath: "/linkding"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-secrets-operator

  managedKubeSecretReferences:
    - secretName: linkding-env-vars
      secretNamespace: linkding
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: linkding-db-user-credentials-infisical
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-d-s7-g

        envSlug: "prod" # "dev", "staging", "prod"
        secretsPath: "/linkding"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-secrets-operator

  managedKubeSecretReferences:
    - secretName: linking-db-user-credentials
      secretNamespace: linkding
      secretType: kubernetes.io/basic-auth
      template:
        data:
          username: "{{ .LD_DB_USER.Value }}"
          password: "{{ .LD_DB_PASSWORD.Value }}"
