apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - secrets.yaml
  - db.yaml
# - service.yaml
# - replicas.yaml
# - version.yaml
# - settings.yaml
