apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: linkding-env-vars-infisical
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-d-s7-g

        envSlug: "prod" # "dev", "staging", "prod"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: linkding-db-user-credentials-infisical
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-d-s7-g

        envSlug: "prod" # "dev", "staging", "prod"
