- name: Create agent config
  template:
    src: ../templates/k3sagent.yaml.j2
    dest: /root/k3sagent.yaml

- name: Install K3s agent
  shell: |
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_EXEC="agent" \
    sh -s - --config=/root/k3sagent.yaml
  args:
    creates: /etc/systemd/system/k3s-agent.service
