apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: traefik-auth-infisical
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: jet-4l4-q

        envSlug: "prod" # "dev", "staging", "prod"
        secretsPath: "/traefik"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-secrets-operator

  managedKubeSecretReferences:
    - secretName: traefik-auth
      secretNamespace: traefik
      template:
        data:
          cloud.conf: "{{ .BASIC_AUTH.Value }}"
