- name: Add Cilium repo
  shell: |
    helm repo add cilium https://helm.cilium.io
    helm repo update

- name: Install Cilium
  shell: |
    KUBECONFIG=/etc/rancher/k3s/k3s.yaml \
    helm upgrade --install cilium cilium/cilium \
      --namespace kube-system \
      --version {{ cilium_version }} \
      --set k8sServiceHost={{ server_ip }} \
      --set k8sServicePort={{ server_port }} \
      --set kubeProxyReplacement=true \
      --set ipam.operator.clusterPoolIPv4PodCIDRList="{{ cluster_cidr }}"
