- name: Fetch kubeconfig
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ./kubeconfig
    flat: true

- name: Replace localhost with server IP
  delegate_to: localhost
  become: false
  replace:
    path: ./kubeconfig
    regexp: '127\.0\.0\.1'
    replace: "{{ server_ip }}"
