apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: koffan-env-vars-infisical
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-d-s7-g

        envSlug: "prod" # "dev", "staging", "prod"
        secretsPath: "/koffan"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-secrets-operator

  managedKubeSecretReferences:
    - secretName: koffan-env-vars
      secretNamespace: koffan
