apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ip-pool.yaml
  - announce.yaml
# patchesStrategicMerge:
#  - db.yaml
# - service.yaml
# - replicas.yaml
# - version.yaml
# - settings.yaml
