apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: "Kinho's Homelab"
    description: "Kubernetes Cluster Entrypoint"
    theme: dark
    color: slate
    cardBlur: md
    headerStyle: boxed
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - icon: github.png
              abbr: GH
              href: https://github.com/k1nho
        - Tailscale:
            - icon: tailscale.png
              abrr: TS
              href: https://login.tailscale.com/admin/machines
        - Infisical:
            - icon: infisical.png
              abbr: IF
              href: https://app.infisical.com

    - Learning:
        - Iximiuz Labs:
            - abbr: IX
              href: https://labs.iximiuz.com/dashboard
            
    - Social:
        - LinkedIn: 
            - icon: linkedin.png
              abbr: IN
              href: https://www.linkedin.com/feed/
        - X:
            - icon: x.png
              abbr: X
              href: https://www.x.com/home/
            
    - Lifestyle:
        - Gmail:
            - icon: gmail.png
              href: https://mail.google.com/mail/u/0/#inbox
        - Bank:
            - icon: sh-bank-of-america
              href: https://www.bankofamerica.com/

  services.yaml: |
    - Core:
        - Argo CD:
            icon: argo-cd.png
            href: https://argo.manakin-koi.ts.net
            description: Argo CD Server (GitOps)
        - Cilium:
            icon: cilium.png
            href: cilium.io
            description: Container Networking Interface
        - Homelab:
            icon: mdi-home-circle
            href: https://github.com/k1nho/homelab
            description: The homelab repository
        - CloudNativePG:
            icon: sh-postgresql
            href: https://cloudnative-pg.io/
            description: CNPG Kubernetes Operator for PostgreSQL database clusters

    - Monitoring:
        - Grafana:
            icon: grafana.png
            href: https://grafana.manakin-koi.ts.net 
            description: Grafana Dashboards (Kube-Prometheus Stack) 
        - Open Cost:
            icon: opencost.png
            href: https://opencost.manakin-koi.ts.net 
            description: Cost monitoring (FinOps) 
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptime-kuma.manakin-koi.ts.net
            description: Monitor Services Uptime (SLA)

    - Services:
        - Linkding :
            icon: linkding.png
            href: https://linkding.manakin-koi.ts.net 
            description: Bookmark Manager 


    - Personal:
        - Blog:
            icon: mdi-post
            href: https://blog.manakin-koi.ts.net
            description: My Personal Blog
        - Homepage:
            icon: sh-homepage
            href: https://homepage.manakin-koi.ts.net 
            description: All in one cluster entrypoint

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
