apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: "Kinho's Homelab"
    description: "Kubernetes Cluster Entrypoint"
    theme: dark
    color: slate
    cardBlur: md
    headerStyle: boxed
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/k1nho
        - Tailscale:
            - abbr: TS
              href: https://login.tailscale.com/admin/machines
        - Infisical:
            - abbr: IF
              href: https://app.infisical.com

    - Social:
        - LinkedIn: 
            - abbr: IN
              href: https://www.linkedin.com/feed/
  services.yaml: |
    - Infrastructure:
        - Argo CD:
            icon: argo-cd.png
            href: https://argo.manakin-koi.ts.net
            description: Argo CD Server (GitOps) 

    - Services:
        - Linkding :
            href: https://linkding.manakin-koi.ts.net 
            description: Bookmark Manager 

    - Personal:
        - Blog:
            href: https://blog.manakin-koi.ts.net
            description: My Personal Blog

  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
