apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: openstack-credentials-infisical
  namespace: kube-system
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: jet-4l4-q

        envSlug: "prod" # "dev", "staging", "prod"
        secretsPath: "/openstack"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-secrets-operator

  managedKubeSecretReferences:
    - secretName: cloud-config
      secretNamespace: kube-system
      creationPolicy: Owner
      template:
        data:
          cloud.conf: "{{ .OPENSTACK_RC.Value }}"
