apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db
spec:
  instances: 3
  storage:
    # storageClass: "local-path"
    size: 1Gi

  imageName: ghcr.io/cloudnative-pg/postgresql:18.3

  # Monitoring
  monitoring:
    enablePodMonitor: true

  # Bootstrap DB
  bootstrap:
    initdb:
      database: linkding
      owner: linkding
      secret:
        name: linkding-db-user-credentials
  # From SQL files
  #   postInitApplicationSQLRefs:
  #     configMapRefs:
  #       - name: post-init
  #         key: post-init.sql
  # ----------------------------
  # From backup
  # recovery:
  #   backup: myBackupObject (from backup object)
  #   source: clusterBackup (from external cluster)
  #   database: db-name
  #   owner: db-owner
  #   secret:
  #     name: db-credentials

  # Backup to object storage
  # backup:
  #   barmanObjectStore:
  #     destinationPath: s3://BUCKET_NAME/path/to/folder
  #     endpointURL: http://custom-endpoint:1234
  #     s3Credentials:
  #       accessKeyId:
  #         name: backup-creds
  #         key: ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: backup-creds
  #         key: ACCESS_SECRET_KEY
  #     wal:
  #       compression: gzip
  #     data:
  #       compression: gzip
  #       encryption: AES256
  #       immediateCheckpoint: false
  #       jobs: 2
  #    retentionPolicy: "30d"

  # resources:
  #   requests:
  #     memory: "512Mi"
  #     cpu: "1"
  #   limits:
  #     memory: "1Gi"

  # Setup Timezones
  # postgresql:
  #   parameters:
  #     timezone: "Europe/Oslo"

  # affinity:
  #   enablePodAntiAffinity: true
  #   topologyKey: failure-domain.beta.kubernetes.io/zone

  # nodeMaintenanceWindow:
  #   inProgress: false
  #   reusePVC: false (no PVC reuse during maintenance)
