deployment:
  kind: DaemonSet

# -- If hostNetwork is true, runs traefik in the host network namespace
# To prevent unschedulable pods due to port collisions, if hostNetwork=true
# and replicas>1, a pod anti-affinity is recommended and will be set if the
# affinity is left as default.
hostNetwork: false

service:
  spec:
    type: ClusterIP

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

# dashboard configuration
api:
  dashboard: true
  insecure: false
  disableDashboardAd:

# Ports configuration (set 80, 443 if running in host network mode)
ports:
  traefik:
    port: 8080
    expose:
      default: false

  web:
    port: 8000
    hostPort: 80
    expose:
      default: true
    exposedPort: 80

  websecure:
    port: 8443
    hostPort: 443
    expose:
      default: true
    exposedPort: 443

providers:
  kubernetesCRD:
    allowCrossNamespace: true # reference middleware from other namespace
