# The homelab charts appset installs all the helm charts defined under envs/homelab
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-charts-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/k1nho/homelab.git
        revision: HEAD
        files:
          - path: "charts/*/envs/homelab/config.json"
  template:
    metadata:
      name: "{{index .path.segments 1}}-{{.env}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{.priority}}"
    spec:
      project: default

      sources:
        # Kustomize for extra resources like secrets or RBAC
        - repoURL: "https://github.com/k1nho/homelab.git"
          targetRevision: HEAD
          path: "charts/{{index .path.segments 1}}/kustomize/envs/{{.env}}"

        # Helm chart source
        - repoURL: "{{.repoURL}}"
          chart: "{{.chart}}"
          targetRevision: "{{.targetRevision}}"
          helm:
            valueFiles:
              - "$values/values/{{index .path.segments 1}}/common-values.yaml"
              - "$values/values/{{index .path.segments 1}}/envs/{{.env}}-values.yaml"

        # Optional extra values
        - repoURL: "https://github.com/k1nho/homelab.git"
          targetRevision: HEAD
          ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"

      # Sync policy with optional ServerSideApply
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply={{ default false (index . "serverSideApply") }}
        automated:
          prune: true
          selfHeal: true
